### ISSUE TITLE
Roof isn't perfectly flat(?)

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#100]
My dropbox is [really filling up with videos from TC](https://www.dropbox.com/s/2vdb854fhwi1f2s/roof.mp4?dl=0).

It's a bit hard to notice but walking on the roof you can tell that you move slightly higher or lower when walking on/off certain roof tiles.

**Comment by ike709** [comment]
This occurs in certain spots all over the roof by the way, you don't need to be in the same spot as the video to replicate.

**Comment by paultech** [comment]
Related to alpha building. Not to be fixed.
