### ISSUE TITLE
Picking up the HWTest floppy and dropping it again causes the floppy to lose its name

### ISSUE THREAD

**Issue by sctjkc01** [techcompliant/TC#104]
While I don't know if the contents get lost as well because we can't insert the floppy into the computers (#60), picking up the floppy spawned in the initial room and dropping it again causes the floppy to lose its label, giving the object a use tooltip of "Use Floppy-5".

**Comment by paultech** [comment]
This is now fixed. All floppies inherit from a common base class, the base class was being used when dropping the item. This is now fixed and drop will create a copy of the top most class in the chain!
