### ISSUE TITLE
Star not bright

### ISSUE THREAD

**Issue by techcompliant** [techcompliant/TC#18]
Star is very close/large but is rather dull when looked at directly.

Need directional light adjustment and possible post-processing changes (Bloom, HBAO)

**Comment by Meisaka** [comment]
Example
<img src=https://i.gyazo.com/9ff40b784be5f270154af620e20cc6da.png>

**Comment by JackFarrand** [comment]
Blow it out completely, complete white out and frag the camera's colour reproduction around it to illustrate exactly what we're dealing with here.  Sun should look as above through polarised windows however, the detail is very nice to look at.

**Comment by paultech** [comment]
Star no longer exists in shown form. Better star system is in place.
