### ISSUE TITLE
Colors displayed wrong on LEM1802

### ISSUE THREAD

**Issue by azertyfun** [techcompliant/TC#20]
Paul kindly offered to test our OS in the game, and the screenshot he gave us showed a green color for our splash screen:

![](http://i.imgur.com/V5UihFo.jpg)

However, it should look like this (works in our emulator and Meisaka's):
![](https://i.imgur.com/xY7qCuE.png)

I would guess that either the LEM1802's color palette isn't cleared on reboot and paul modified it beforehand, or there is a mismatch between the green and blue components.

**Comment by paultech** [comment]
Fixed with move to new emulator and texture format fix.
