### ISSUE TITLE
Loading Game is jarring, perhaps add Loading Screen

### ISSUE THREAD

**Issue by clonk2u** [techcompliant/TC#22]
When you hit play in game, the game freezes as it loads everything. This also leads to issues with sound and non responsive clicking, perhaps a loading screen would help.

**Comment by paultech** [comment]
Level streaming is setup, I just need to place a loading level for intermediate. On the todo

**Comment by JackFarrand** [comment]
something simple like one of these will do it I should think: https://www.reddit.com/r/loadingicon/top/?sort=top&t=all

**Comment by paultech** [comment]
Added loading screen.
