### ISSUE TITLE
Switches need larger side to side area.

### ISSUE THREAD

**Issue by clonk2u** [techcompliant/TC#23]
As It stands for most switches you have to be really close to operate them and standing directly in front of them, increasing the interaction ares on each side should improve this and increase realism.

**Comment by JackFarrand** [comment]
Second

**Comment by paultech** [comment]
Switches can now be triggered with 'e' along with the normal mouse dragging. I can increase the collision box if it still not comfortable for you guys! Let me know after RC6.
