### ISSUE TITLE
LEM and memory not reset after "Reboot"

### ISSUE THREAD

**Issue by Meisaka** [techcompliant/TC#25]
<img src=https://i.gyazo.com/55f102abe9ad9492cc726249e7ae33d9.png>

**Comment by paultech** [comment]
The texture and backing array are not scrubbed during disconnect/connect() so they don't reset.

**Comment by Meisaka** [comment]
I should probably clarify: if one loaded DCPU program sets a custom font/palette, then another is inserted and the DCPU is "Rebooted", this is the result: the custom font and/or palette from the last program is still in effect.

**Comment by paultech** [comment]
Oh that's interesting, They should be reset back to defaults on disconnect(). Will check what's going on there.

Thanks

**Comment by paultech** [comment]
Fixed with move to new emulator.
