### ISSUE TITLE
Issue with text on LEM-1802 screens

### ISSUE THREAD

**Issue by andyleap** [techcompliant/TC#28]
Here's a screenie of the issue.

http://i.imgur.com/GQ1K0pe.png

Happens with texture quality set to high, problem is still there but less pronounced on Epic.

**Comment by paultech** [comment]
Believe I have this fixed in RC6 with changes to the PCX_16 post processing camera. Leaving open to get confirmation of that.

**Comment by paultech** [comment]
Fixed with move to new emulator and texture format correction.
