### ISSUE TITLE
Join Sandbox twice duplicates server listings

### ISSUE THREAD

**Issue by shazow** [techcompliant/TC#37]
To reproduce:
1. Join Sandbox, sign in
2. Get server list
3. Join Sandbox again, sign in
4. Get server list with each server listed twice

**Comment by paultech** [comment]
Fixed in next build.

Widget Servers - Clears children on GetServerList()
Widget MainMenu - If join station is clicked while a valid auth token is present, show server list - not login.

Thanks!
