### ISSUE TITLE
Stuck in /dance loop

### ISSUE THREAD

**Issue by shazow** [techcompliant/TC#39]
I was /dance'ing, then got into a car, and I was forever stuck in the dance loop. Also couldn't get out of the car.

**Comment by paultech** [comment]
Confirmed, fixing the ever lasting dance.

**Comment by shazow** [comment]
Suggested soundtrack while fixing the bug: https://www.youtube.com/watch?v=3Q9rewnLFYw

**Comment by paultech** [comment]
Animation driving has been overhauled, new montage system in place. No more ever lasting dance.

**Comment by shazow** [comment]
Rest in peace, eternal dance.
