### ISSUE TITLE
lem graphics problem

### ISSUE THREAD

**Issue by orlof** [techcompliant/TC#41]
[Test program](https://github.com/orlof/dcpu-test) shows [this](http://i.imgur.com/XQfree3.png) in my emulator, but [this](http://i.imgur.com/oXEgtYX.png) in TC.

If you look closely there are lot of differences in font graphics e.g. the bottom line. I suppose TC is in error here.

**Comment by andyleap** [comment]
Should be fixed in the next patch, there was an issue with replication only working for the first 64 glyphs of the font memory.

**Comment by paultech** [comment]
Confirmed fixed
