### ISSUE TITLE
Windows Itch PlayTest build can not be run without Vulkan libs

### ISSUE THREAD

**Issue by Mrrraou** [techcompliant/TC#42]
The Windows Itch PlayTest build can not run without a library called "vulkan-1".
This seems to make GPUs without Vulkan support on their drivers unable to run the build.
(My GPU is kind of old, and does not support Vulkan at all)

**Comment by paultech** [comment]
Vulkan bug finally fixed. No longer attempts to include the Vulkan render on desktop builds!
