### ISSUE TITLE
Another tab in the settings menu?

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#46]
![image](https://cloud.githubusercontent.com/assets/5714543/21469049/50271f42-c9fc-11e6-87c5-e5af81d9be96.png)

Look at the red box I drew. It looks like there is/should be a Game tab in the menu, but clicking it does nothing and it lacks the background other tabs have.

**Comment by paultech** [comment]
Yes, those are supposed to be disabled on non staff/debug build but I appear to have not set visibility on the text child. 

Will fix

**Comment by paultech** [comment]
Fixed in 0.0.8
