### ISSUE TITLE
A suggestion (Because I can't be bothered to begin to understand how Reddit works)

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#50]
Create a public [Trello](https://trello.com/) board that shows things like what you're currently working on, what's fixed in the next patch, etc. like as seen [here](https://trello.com/b/wXLmhG5y/angels-fall-first-roadmap) or [here](https://trello.com/b/kQIDRHcc/wild-west) or [here](https://trello.com/b/gHooNW9I/ue4-roadmap).

It'd probably be tedious to constantly update it with small bugs/features/whatever, but it'd be nice to see what's being worked on. And like some games, even allow users to vote on the trello cards to determine what'll be prioritized.

**Comment by paultech** [comment]
https://trello.com/techcompliant

However, needs updated with more recent information.
