### ISSUE TITLE
Settings menu text inconsistency

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#52]
![image](https://cloud.githubusercontent.com/assets/5714543/21469180/f330073e-ca02-11e6-86b4-e6f4af33f0e9.png)
![image](https://cloud.githubusercontent.com/assets/5714543/21469182/f7150bec-ca02-11e6-86eb-d5c8e6be538a.png)

Text is yellow (or whatever color that is) on the audio tab, but black on the other tabs. The settings menu on the main menu and the settings menu ingame both have this issue.

Also, there's no visual indication of which tab you're on while browsing the main menu settings, like how the other tab buttons darken on the ingame settings menu when you select a tab.

**Comment by paultech** [comment]
Fixed in 0.0.8
