### ISSUE TITLE
Item bar bugs

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#59]
![image](https://cloud.githubusercontent.com/assets/5714543/21469499/76528b50-ca17-11e6-83d2-894a0c73c998.png)

Three major bugs with the item bar:

1. Items appear behind the translucent circles, but I assume they should appear above.
2. Items placed in the item bar from the inventory will be duplicated, leaving the item behind in your inventory _and_ adding one to your item bar.
3. There's 8 slots but a keyboard has 10 number buttons. (1 through 9 plus 0 at the end)
4. Is that thing actually called an item bar? What the hell is the technical term for those?

There's also potentially a bug with items vanishing seemingly randomly from the item bar but I haven't been able to replicate it beyond seeing it mysteriously happen once. I might've just dropped the item or something.

**Comment by ike709** [comment]
Okay so after actually spending more than 30 seconds on this:

I think number 2 may either intentionally or unintentionally not actually be an issue. If I'm right, it's still an extremely silly thing that needs to be changed.

When you move an item to your item bar, it doesn't seem to really be "there" because removing it just clears the item from your item bar, it doesn't drop or anything. I think it's just supposed to be a "reference" to the item in your inventory, because when you press 1 or 2 on your keyboard with an item in those slots, the item will physically move (not copy) from your inventory to your main or off hand.

But whether "intentional" or a bug, it's an extremely silly mechanic and I think that it should just actually move from inventory to item bar. You can still have the "pressing 1 or 2 makes it appear in my hands" thing, but then the Hands slots in the Equipment tab should just become images, not movable objects.

Note: Item bar/Hand interaction only works with slots 1 and 2 on the item bar.

**Comment by paultech** [comment]
I think the plan/solution here is to remove the "hotbar" and replace with a humanoid diagram showing equipment slots and status. Also solving #64 in the process.

**Comment by paultech** [comment]
Fixed in next release. Overhauled inventory system.
