### ISSUE TITLE
How the hell do you put a floppy in the computers?

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#60]
I've gotten as far as the "Select Floppy" screen, but I see no way of moving the floppy from my inventory to the computer.

**Comment by paultech** [comment]
Currently broken, fixed in next build -> Clientside copy of the inventory was not updating correctly so you could not see the floppies you picked up in the UI.

**Comment by paultech** [comment]
Fixed in next release. Confirmed fixed
