### ISSUE TITLE
Computer power button does nothing

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#61]
![image](https://cloud.githubusercontent.com/assets/5714543/21469510/de3e2bf6-ca18-11e6-82eb-7061fc7f39de.png)

Nothing happens when you click the power button. It doesn't turn off, and it doesn't "reset" as the tooltip says it will do, because the "No bootable media found" spam I created did not disappear.

**Comment by paultech** [comment]
This one is already fixed in next patch!

**Comment by paultech** [comment]
Fixed in next release. Confirmed fixed
