### ISSUE TITLE
Camera is a bit off(?)

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#63]
![image](https://cloud.githubusercontent.com/assets/5714543/21469543/1bbeb9c6-ca1b-11e6-973f-3ce7e2a068d4.png)

If you look straight down, you can see your body is turned to the right slightly. Is the camera a bit off relative to the model, or is this just the correct perspective/odd model?

**Comment by ike709** [comment]
Also, that's just an example. You can tell long before you're looking straight down.

**Comment by paultech** [comment]
Ah yes, seen that one myself. Willfix

**Comment by ghost** [comment]
Something about it makes me feel sick, feels like it pivots differently than other games do it.

**Comment by paultech** [comment]
Camera overhauled in 0.0.8 -> Camera switching in MP is functional again and more sane values for camera placement. Can no longer look down your own neck.
