### ISSUE TITLE
No visual indication for equipped items

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#64]
When you equip an item in your item bar by pressing 1-8 (Oh boy, more item bar issues), you can see by looking down that the item _is_ equipped in your hand, but the item should be highlighted or something in the item bar so you _don't_ have to look down to check.

Maybe change the color of the slot circle or make it bigger or something?

**Comment by ike709** [comment]
Might want to see my latest comment on #59 as well. May be linked.

**Comment by paultech** [comment]
Fixed in next release.  Overhauled inventory/equipment system.
