### ISSUE TITLE
Interior Doors replication issue

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#68]
![image](https://cloud.githubusercontent.com/assets/5714543/21469587/565aaf1e-ca1f-11e6-83ac-a180c3c5ed2f.png)

Not sure if you saw my message in chat, so there you go. They worked not at all earlier today, they worked fine after that, and now they work weirdly.

**Comment by paultech** [comment]
Join in-progress of the door state and it the behavior associated with that is broken so the server and client have very different states on where the door should be placed resulting in the awful behavior for the user. Isfixed in next patch.

Part of the reason for the intermittent nature is the server has been restarted a few time when player count is zero to reset the rockets and a few other items resulting in you may being the first to join and having proper state, only when you join after states have been adjusted.

**Comment by paultech** [comment]
Additional note: Chat issues are a little confusing on two fronts. One the default /say only covers a certain radius, /yell increases that but due the previous social issue the chat also suffers from intermittent issues to be fixed with non-sharing of accounts for proper player data loading.

**Comment by paultech** [comment]
Fixed in next release.
