### ISSUE TITLE
Triggered (heh)

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#69]
![image](https://cloud.githubusercontent.com/assets/5714543/21469600/6753a6da-ca20-11e6-8202-6a1996a23bdc.png)
There's no indication of anything happening when you Use one of those lever triggers. The handle doesn't change position, and the text doesn't change.

**Comment by paultech** [comment]
Rockets were thrown in sort of last second, I do have a fully functional switch but it was tied into the wire system that didn't play very well with a moving rocket! Solution is to add additional logic to the full switch component that can handle wireless 'virtual' links.

**Comment by paultech** [comment]
Old temp switches removed. Proper moving switches in place! In next patch.

**Comment by paultech** [comment]
All new controls in place with proper animations & effects!
