### ISSUE TITLE
Broken Commander == Broken Game

### ISSUE THREAD

**Issue by clonk2u** [techcompliant/TC#7]
IF you break the monitor off the commander while its running, the game will crash. Only happens after screen of commander goes dead and crash happens faster after leaving game running for a while before initiating bug.

**Comment by JackFarrand** [comment]
by god he's solved it, that's what did it for me too

**Comment by techcompliant** [comment]
Removal of auto-disconnect functionality in RC5 to confirm this was the crash problem.

**Comment by paultech** [comment]
This was resolved by overhauling the way CPUComponent and the DCPUServer streamed textures and fixed a issue with early garbage collection invalidating it a few frames early (thread out of lockstep).
