### ISSUE TITLE
Closing the settings menu

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#71]
Here we go again...

If you close the settings menu ingame by clicking OK, you won't be able to walk around and you won't have a crosshair or cursor. But pressing Alt (ToggleMouse) will fix it.

I think when the menu is closed by clicking OK, it closes but leaves you in the ToggleMouse mode where you'd normally move your cursor around the screen, except your cursor is invisible/nonexistent.

**Comment by paultech** [comment]
Fixed in 0.0.8
