### ISSUE TITLE
You can easily break the inventory windows

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#80]
![image](https://cloud.githubusercontent.com/assets/5714543/21473157/4412569c-cac2-11e6-9254-407ddfbed22c.png)

Y'know how the Settings menu has that "Move Menu" feature by clicking and dragging the blue bar at the top? Try doing that with the Equipment or Inventory screen by clicking in the red boxes I drew in the picture above. The one you click will move closer and closer to the edge of the screen every time you click it, until it is gone forever and you can never make them reappear unless you restart the game.

**Comment by ike709** [comment]
ACTUALLY, you can click pretty much anywhere on Equipment or Inventory, and unless it's an item slot, the menu will move. That makes it _even easier_ to break it.

**Comment by paultech** [comment]
Ability to drag windows disabled in UI untill upstream engine bugs are fixed:

[UE-31777](https://issues.unrealengine.com/issue/UE-31777)
[UE-39106](https://issues.unrealengine.com/issue/UE-39106)
