### ISSUE TITLE
Windowed/Fullscreen/Windowed Fullscreen Issues

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#83]
Windowed isn't truly windowed. The Windows taskbar will appear at the bottom, but no bar will appear at the top of the program with the name of the program and Minimize, Restore, Close buttons in the top right.

Fullscreen and Windowed Fullscreen are exactly the same, both allowing you to use your mouse on your second monitor as if Tech Compliant were borderless.

**Comment by andyleap** [comment]
These all work perfectly.  If you try to set windowed to as large as your monitor, it'll automatically drop the title bar and other "window decorations".  Back the res down and they will appear.  Furthermore, mouse movement has nothing to do with windowed fullscreen vs. fullscreen, the key difference is on the graphics card/driver side.  Windowed fullscreen is just what it says, and allows other windows to be dragged on top of it and such.  You also get faster alt-tabbing.  However, the game gets slightly less resources and control as a result.  Standard fullscreen will not allow you to drag other windows over it, and alt-tabbing is slower.
