### ISSUE TITLE
Camera sensitivity is off the charts!

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#84]
![image](https://cloud.githubusercontent.com/assets/5714543/21473227/4c915206-cac6-11e6-9317-25b03620d390.png)

While setting a sensitivity less than 0 will revert it to 0.1, setting a sensitivity over 100 by typing it in the box will not revert to 100. It just sends the slider off the menu, and will result in a sensitivity that _seems_ faster than 100, but I can't confirm that it really is faster than 100.

**Comment by andyleap** [comment]
Sensitivity settings now clamp to proper range via textbox as well.  Should be in next patch
