### ISSUE TITLE
The amount of support beams holding up the base seems excessive

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#88]
![image](https://cloud.githubusercontent.com/assets/5714543/21485921/e860a24a-cb70-11e6-8a5b-0b296d416eb2.png)

There's literally as many support columns as possible underneath the base. Seems unrealistic. Like one per buildable section of floor maybe, I don't know.

Honestly, building it up on top of support beams at all seems unrealistic but I assume there's issues with the ground clipping through the floor or something.

**Comment by ike709** [comment]
Plus I want to be able to adventure underneath the base but those things are blocking my path.

**Comment by paultech** [comment]
They were put there a bit place holder as they are the previous foundation from base building concept. Will be improved at some point!

**Comment by paultech** [comment]
Fixed/reduced supports.
