### ISSUE TITLE
Multiple lighting issues

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#95]
![image](https://cloud.githubusercontent.com/assets/5714543/21575614/073b509c-ced8-11e6-90d8-a85a5b9b1c67.png)
(Image taken from #94)

That lever in the base by the DCPUs is like totally pitch black on default settings. You're only capable of seeing it if you crank the Gamma way up. But there's nothing blocking the light shining on it.

**Comment by ike709** [comment]
The original post is the first lighting issue. This comment is the second. Not sure whether I should have made a separate issue or condensed them both into this one, but I did the latter.

![image](https://cloud.githubusercontent.com/assets/5714543/21575737/5932dfba-cedc-11e6-8a98-aca1c38eac72.png)
Light seeps through the walls.

**Comment by paultech** [comment]
Related to alpha building. Not to be fixed.
