### ISSUE TITLE
The top of the walls don't have a texture, and random things stick through the base roof

### ISSUE THREAD

**Issue by ike709** [techcompliant/TC#99]
![image](https://cloud.githubusercontent.com/assets/5714543/21583173/5347e7d0-d03a-11e6-9989-f666b65fbf7f.png)
![image](https://cloud.githubusercontent.com/assets/5714543/21583176/64663b0c-d03a-11e6-83c1-8911a56fbd2d.png)

The first picture is hopefully self-explanatory, but in the second one you can see in my special little boxes that there's random thingies sticking up out of the base roof everywhere. I assume it's part of interior doors or something.

**Comment by ike709** [comment]
Presumably related to the other issues involving missing wall textures, #43 and #65

**Comment by paultech** [comment]
Related to alpha building. Not to be fixed.
